### PR TITLE
Rachel and Ryan Indian Country

### PR DESCRIPTION
**Pull request by rachelkakos**

### CODE REVIEW

**Review by 0Redfeather — APPROVED** [review]
@harr1516 @rachelkakos The work for your pull request looks great, but it has turned out a little weird. I think that since Rachel was using a desktop mac from the lab, your commits were coming through as changes from someone else. I'm going to write down Rachel (@rachelkakos ) and Ryan (harr151) for the credit for this homework, but **can you confirm these are the GitHub usernames that you used to send in this pull request?** Thanks

**Comment by harr1516** [comment]
Hi,

My Github username is harr1516 (not harr151) just to clarify, but yes the submissions were appearing as if it was from a different person.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 0Redfeather** [comment]
@harr1516 Awesome thanks. I'll set up the computer so next time @rachelkakos can sign in and submit as themselves. Good work guys.

**Comment by rachelkakos** [comment]
Hi Zach,
Yes the computer was actually saying that it was sending as Jack Biggs. We figured it was because he had previously signed in on the desktop. Anyhow, my username is @rachelkakos. If you have any other questions let me know.
Best,
Rachel

**Comment by harr1516** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
