### PR TITLE
Turn-in 

### PR DESCRIPTION
**Pull request by clairemcreynolds415**
Put image and caption

### CODE REVIEW

**Review by 0Redfeather — CHANGES_REQUESTED** [review]
Hello, this looks really good but there are a couple of changes I would request when it comes to your <figure> code. This mainly has to do with the naming convention we are now using:
- change the name of your image file to all lower case - tribalentities.jpeg
- change the code in your project HTML (at line 40) to lower case as well since calling the code is still case sensitive
- Also, the "percentage of tribal entities and non-tribal band Providers" in line 41 is kind of extra. This content could be put inside the data-content="" section. or where the Image 1 is.

**Comment by clairemcreynolds415** [comment]
I made the changes but now the image won't show up on the website. I changed the image file to all lower case and the HTML.
________________________________

**Comment by clairemcreynolds415** [comment]
changes made

**Comment by 0Redfeather** [comment]
Awesome, all you have to do to make the image show up is also lower case the name of your actual image file from Broadband.jpeg to broadband.jpeg and it should appear. Otherwise, everything looks great, good job!

**Review by 0Redfeather — APPROVED** [review]

**Pull request merged**
